version: "3.8"

services:
  fastapi:
    image: fastapi:latest
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    working_dir: /code/app
    volumes:
      - ./app:/code/app
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    restart: on-failure

volumes:
  mongodb_data:
